import { Routes, Route, Navigate, Link } from 'react-router-dom';
import { useEffect, useState } from 'react';
import api from './api/client';
import { PieChart, Pie, Cell, ResponsiveContainer } from 'recharts';

function Login(){const [email,setEmail]=useState('admin@agenda.com'); const [senha,setSenha]=useState('admin123'); const submit=async()=>{const {data}=await api.post('/auth/login',{email,senha}); localStorage.setItem('token',data.token); location.href='/';}; return <div className='min-h-screen flex items-center justify-center'><div className='bg-white p-6 rounded shadow w-80 space-y-2'><h1 className='text-xl font-bold'>Agenda</h1><input className='border p-2 w-full' value={email} onChange={e=>setEmail(e.target.value)}/><input className='border p-2 w-full' type='password' value={senha} onChange={e=>setSenha(e.target.value)}/><button className='bg-blue-600 text-white px-4 py-2 rounded w-full' onClick={submit}>Entrar</button></div></div>}

function Layout({children}){return <div className='flex min-h-screen'><aside className='w-56 bg-slate-900 text-white p-4 space-y-2'><Link to='/'>Dashboard</Link><br/><Link to='/contatos'>Contatos</Link><br/><Link to='/categorias'>Categorias</Link></aside><main className='flex-1 p-6'>{children}</main></div>}

function Dashboard(){const [d,setD]=useState(null); useEffect(()=>{api.get('/dashboard').then(r=>setD(r.data));},[]); if(!d)return '...'; const pie=Object.entries(d.byCategory).map(([name,value])=>({name,value})); return <div><h2 className='text-2xl font-bold'>Dashboard</h2><p>Total: {d.total}</p><div className='h-64'><ResponsiveContainer><PieChart><Pie data={pie} dataKey='value'>{pie.map((_,i)=><Cell key={i} fill={['#2563eb','#7c3aed','#059669','#f59e0b'][i%4]}/> )}</Pie></PieChart></ResponsiveContainer></div></div>}

function Contatos(){const [list,setList]=useState([]);const [nome,setNome]=useState('');const load=()=>api.get('/contatos').then(r=>setList(r.data));useEffect(load,[]);const add=async()=>{await api.post('/contatos',{nome,status:'ativo'});setNome('');load();};return <div><h2 className='text-2xl font-bold mb-2'>Contatos</h2><div className='flex gap-2 mb-3'><input className='border p-2' value={nome} onChange={e=>setNome(e.target.value)} placeholder='Nome'/><button className='bg-blue-600 text-white px-3 rounded' onClick={add}>Adicionar</button></div><table className='w-full bg-white'><thead><tr><th>Nome</th><th>Empresa</th><th>Status</th></tr></thead><tbody>{list.map(c=><tr key={c.id}><td>{c.nome}</td><td>{c.empresa}</td><td>{c.status}</td></tr>)}</tbody></table></div>}

function Categorias(){const [list,setList]=useState([]);const [nome,setNome]=useState('');const load=()=>api.get('/categorias').then(r=>setList(r.data));useEffect(load,[]);const add=async()=>{await api.post('/categorias',{nome});setNome('');load();};return <div><h2 className='text-2xl font-bold mb-2'>Categorias</h2><div className='flex gap-2 mb-3'><input className='border p-2' value={nome} onChange={e=>setNome(e.target.value)}/><button className='bg-blue-600 text-white px-3 rounded' onClick={add}>Adicionar</button></div>{list.map(c=><div key={c.id} className='bg-white p-2 mb-1 rounded'>{c.nome}</div>)}</div>}

const Private = ({children}) => localStorage.getItem('token') ? <Layout>{children}</Layout> : <Navigate to='/login'/>;
export default function App(){return <Routes><Route path='/login' element={<Login/>}/><Route path='/' element={<Private><Dashboard/></Private>}/><Route path='/contatos' element={<Private><Contatos/></Private>}/><Route path='/categorias' element={<Private><Categorias/></Private>}/></Routes>}
